# Generated by Django 5.1.6 on 2025-06-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataliticos', '0002_compracatalitico_cliente_apellido_cliente_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalitico',
            name='galeria',
            field=models.ImageField(blank=True, null=True, upload_to='cataliticos/'),
        ),
        migrations.AddField(
            model_name='catalitico',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='cataliticos/'),
        ),
    ]
