# Generated by Django 5.1.6 on 2025-06-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.PositiveIntegerField(default=0)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='cataliticos/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='cataliticos/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='cataliticos/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='cataliticos/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompraCatalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_telefono', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_apellido', models.CharField(blank=True, max_length=100)),
                ('cliente_rut', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cataliticos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCatalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.PositiveIntegerField()),
                ('catalitico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cataliticos.catalitico')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cataliticos.compracatalitico')),
            ],
        ),
    ]
