# Generated by Django 5.1.6 on 2025-06-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='media/img/imagenes_cataliticos/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='media/img/imagenes_cataliticos/')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='media/img/imagenes_cataliticos/')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='media/img/imagenes_cataliticos/')),
                ('valor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompraCatalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_rut', models.CharField(blank=True, max_length=20)),
                ('valor_ofrecido', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('catalitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataliticos.catalitico')),
            ],
        ),
    ]
