# Generated by Django 5.1.6 on 2025-06-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataliticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('platino', models.FloatField(help_text='Variación porcentual diaria del platino')),
                ('paladio', models.FloatField(help_text='Variación porcentual diaria del paladio')),
                ('rodio', models.FloatField(blank=True, help_text='Variación del rodio (solo se usa 1 y 15 de cada mes)', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='catalitico',
            name='valor_actual',
            field=models.IntegerField(default=0),
        ),
    ]
