# Generated by Django 4.2.22 on 2025-06-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataliticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalitico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
