# Generated by Django 5.1.6 on 2025-07-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataliticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoChatarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('precio_kg', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='chatarra/')),
            ],
        ),
    ]
