# Generated by Django 5.1.6 on 2025-06-06 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataliticos', '0002_alter_catalitico_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalitico',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='catalitico',
            name='valor_estimado',
        ),
        migrations.AddField(
            model_name='catalitico',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='cataliticos/'),
        ),
        migrations.AddField(
            model_name='catalitico',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='cataliticos/'),
        ),
        migrations.AddField(
            model_name='catalitico',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='cataliticos/'),
        ),
        migrations.AddField(
            model_name='catalitico',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='cataliticos/'),
        ),
        migrations.CreateModel(
            name='CompraCatalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_rut', models.CharField(blank=True, max_length=20)),
                ('valor_ofrecido', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('catalitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataliticos.catalitico')),
            ],
        ),
    ]
