# Generated by Django 5.1.6 on 2025-07-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataliticos', '0002_productochatarra'),
    ]

    operations = [
        migrations.AddField(
            model_name='productochatarra',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
