# Generated by Django 5.1.6 on 2025-06-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataliticos', '0002_preciometal_catalitico_valor_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
