# Generated by Django 5.1.6 on 2025-06-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataliticos', '0003_catalitico_galeria_catalitico_imagen_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracatalitico',
            name='cliente_apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
