# Generated by Django 5.1.6 on 2025-06-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataliticos', '0003_remove_catalitico_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalitico',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
