# Generated by Django 5.1.6 on 2025-06-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataliticos', '0004_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compracatalitico',
            name='cliente_rut',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
