# Generated by Django 5.1.6 on 2025-06-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataliticos', '0004_compracatalitico_cliente_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalitico',
            old_name='galeria',
            new_name='imagen2',
        ),
        migrations.AddField(
            model_name='catalitico',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='cataliticos/'),
        ),
        migrations.AddField(
            model_name='catalitico',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='cataliticos/'),
        ),
    ]
