
services:
  - type: web
    name: cataliticos
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn cataliticos_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cataliticos_project.settings
      - key: PYTHON_VERSION
        value: 3.9
